services:
  frontend:
    extends:
      file: "frontend/docker-compose.yml"
      service: lpg-normalization-frontend
    profiles:
      - grana-grano
    networks:
      - app-network

  neo4j:
    extends:
      file: "backend/docker-compose.yml"
      service: neo4j
    volumes:
      - ./backend/graphs:/tmp/graphs
    networks:
      - app-network
    profiles:
      - grana-grano

  memgraph:
    extends:
      file: "backend/docker-compose.yml"
      service: memgraph
    networks:
      - app-network
    profiles:
      - grana-grano
    volumes:
      - ./backend/graphs:/graphs

  restapi:
    extends:
      file: "backend/docker-compose.yml"
      service: restapi
    env_file:
      - path: ./backend/.env
    environment:
      URL_PREFIX: "/api"
    networks:
      - app-network
    profiles:
      - grana-grano

  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./assets/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    networks:
      - app-network
    profiles:
      - grana-grano

networks:
  app-network:
    driver: bridge
