services:
  frontend:
    extends:
      file: "frontend/docker-compose.yml"
      service: lpg-normalization-frontend
    environment:
      API_ENDPOINT: "/api"
    profiles:
      - grana-grano
    networks:
      - app-network

  neo4j:
    extends:
      file: "backend/docker-compose.yml"
      service: neo4j
    networks:
      - app-network
    profiles:
      - grana-grano

  memgraph:
    extends:
      file: "backend/docker-compose.yml"
      service: memgraph
    networks:
      - app-network
    profiles:
      - grana-grano

  restapi:
    extends:
      file: "backend/docker-compose.yml"
      service: restapi
    env_file:
      - path: ./backend/.env
    environment:
      URL_PREFIX: "/api"
    networks:
      - app-network
    profiles:
      - grana-grano

  reverse-proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    profiles:
      - grana-grano

networks:
  app-network:
    driver: bridge
